version: "3"
services:
  backend:
    image: "backend"
    build:
      context: .
    volumes:
      - .:/go/src/app
    env_file:
      - env_vars.env
    depends_on:
      - db

  db:
    image: mongo